//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1beta1 "github.com/gardener/gardener/pkg/apis/core/v1beta1"
	extensionsv1alpha1 "github.com/gardener/gardener/pkg/apis/extensions/v1alpha1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"

	gdc "github.com/gardener/gardener-extension-provider-gdc/pkg/apis/gdc"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*BackupBucketConfig)(nil), (*gdc.BackupBucketConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BackupBucketConfig_To_gdc_BackupBucketConfig(a.(*BackupBucketConfig), b.(*gdc.BackupBucketConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.BackupBucketConfig)(nil), (*BackupBucketConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_BackupBucketConfig_To_v1alpha1_BackupBucketConfig(a.(*gdc.BackupBucketConfig), b.(*BackupBucketConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudProfileConfig)(nil), (*gdc.CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudProfileConfig_To_gdc_CloudProfileConfig(a.(*CloudProfileConfig), b.(*gdc.CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.CloudProfileConfig)(nil), (*CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(a.(*gdc.CloudProfileConfig), b.(*CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneConfig)(nil), (*gdc.ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControlPlaneConfig_To_gdc_ControlPlaneConfig(a.(*ControlPlaneConfig), b.(*gdc.ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.ControlPlaneConfig)(nil), (*ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(a.(*gdc.ControlPlaneConfig), b.(*ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureConfig)(nil), (*gdc.InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureConfig_To_gdc_InfrastructureConfig(a.(*InfrastructureConfig), b.(*gdc.InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.InfrastructureConfig)(nil), (*InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(a.(*gdc.InfrastructureConfig), b.(*InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureStatus)(nil), (*gdc.InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureStatus_To_gdc_InfrastructureStatus(a.(*InfrastructureStatus), b.(*gdc.InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.InfrastructureStatus)(nil), (*InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(a.(*gdc.InfrastructureStatus), b.(*InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImage)(nil), (*gdc.MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImage_To_gdc_MachineImage(a.(*MachineImage), b.(*gdc.MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.MachineImage)(nil), (*MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_MachineImage_To_v1alpha1_MachineImage(a.(*gdc.MachineImage), b.(*MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImageFlavor)(nil), (*gdc.MachineImageFlavor)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImageFlavor_To_gdc_MachineImageFlavor(a.(*MachineImageFlavor), b.(*gdc.MachineImageFlavor), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.MachineImageFlavor)(nil), (*MachineImageFlavor)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_MachineImageFlavor_To_v1alpha1_MachineImageFlavor(a.(*gdc.MachineImageFlavor), b.(*MachineImageFlavor), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImageVersion)(nil), (*gdc.MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImageVersion_To_gdc_MachineImageVersion(a.(*MachineImageVersion), b.(*gdc.MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.MachineImageVersion)(nil), (*MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_MachineImageVersion_To_v1alpha1_MachineImageVersion(a.(*gdc.MachineImageVersion), b.(*MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImages)(nil), (*gdc.MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImages_To_gdc_MachineImages(a.(*MachineImages), b.(*gdc.MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.MachineImages)(nil), (*MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_MachineImages_To_v1alpha1_MachineImages(a.(*gdc.MachineImages), b.(*MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkConfig)(nil), (*gdc.NetworkConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkConfig_To_gdc_NetworkConfig(a.(*NetworkConfig), b.(*gdc.NetworkConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.NetworkConfig)(nil), (*NetworkConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_NetworkConfig_To_v1alpha1_NetworkConfig(a.(*gdc.NetworkConfig), b.(*NetworkConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkStatus)(nil), (*gdc.NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkStatus_To_gdc_NetworkStatus(a.(*NetworkStatus), b.(*gdc.NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.NetworkStatus)(nil), (*NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_NetworkStatus_To_v1alpha1_NetworkStatus(a.(*gdc.NetworkStatus), b.(*NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OrgConfig)(nil), (*gdc.OrgConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OrgConfig_To_gdc_OrgConfig(a.(*OrgConfig), b.(*gdc.OrgConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.OrgConfig)(nil), (*OrgConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_OrgConfig_To_v1alpha1_OrgConfig(a.(*gdc.OrgConfig), b.(*OrgConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Storage)(nil), (*gdc.Storage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Storage_To_gdc_Storage(a.(*Storage), b.(*gdc.Storage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.Storage)(nil), (*Storage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_Storage_To_v1alpha1_Storage(a.(*gdc.Storage), b.(*Storage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SubnetReference)(nil), (*gdc.SubnetReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SubnetReference_To_gdc_SubnetReference(a.(*SubnetReference), b.(*gdc.SubnetReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.SubnetReference)(nil), (*SubnetReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_SubnetReference_To_v1alpha1_SubnetReference(a.(*gdc.SubnetReference), b.(*SubnetReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkerConfig)(nil), (*gdc.WorkerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkerConfig_To_gdc_WorkerConfig(a.(*WorkerConfig), b.(*gdc.WorkerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.WorkerConfig)(nil), (*WorkerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_WorkerConfig_To_v1alpha1_WorkerConfig(a.(*gdc.WorkerConfig), b.(*WorkerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkerStatus)(nil), (*gdc.WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkerStatus_To_gdc_WorkerStatus(a.(*WorkerStatus), b.(*gdc.WorkerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.WorkerStatus)(nil), (*WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_WorkerStatus_To_v1alpha1_WorkerStatus(a.(*gdc.WorkerStatus), b.(*WorkerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Zone)(nil), (*gdc.Zone)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Zone_To_gdc_Zone(a.(*Zone), b.(*gdc.Zone), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.Zone)(nil), (*Zone)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_Zone_To_v1alpha1_Zone(a.(*gdc.Zone), b.(*Zone), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ZoneEndpoints)(nil), (*gdc.ZoneEndpoints)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ZoneEndpoints_To_gdc_ZoneEndpoints(a.(*ZoneEndpoints), b.(*gdc.ZoneEndpoints), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.ZoneEndpoints)(nil), (*ZoneEndpoints)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_ZoneEndpoints_To_v1alpha1_ZoneEndpoints(a.(*gdc.ZoneEndpoints), b.(*ZoneEndpoints), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Zones)(nil), (*gdc.Zones)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Zones_To_gdc_Zones(a.(*Zones), b.(*gdc.Zones), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*gdc.Zones)(nil), (*Zones)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_gdc_Zones_To_v1alpha1_Zones(a.(*gdc.Zones), b.(*Zones), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_BackupBucketConfig_To_gdc_BackupBucketConfig(in *BackupBucketConfig, out *gdc.BackupBucketConfig, s conversion.Scope) error {
	out.DualZoneBucketLocation = in.DualZoneBucketLocation
	out.RequestChecksumCalculation = in.RequestChecksumCalculation
	out.ResponseChecksumValidation = in.ResponseChecksumValidation
	return nil
}

// Convert_v1alpha1_BackupBucketConfig_To_gdc_BackupBucketConfig is an autogenerated conversion function.
func Convert_v1alpha1_BackupBucketConfig_To_gdc_BackupBucketConfig(in *BackupBucketConfig, out *gdc.BackupBucketConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_BackupBucketConfig_To_gdc_BackupBucketConfig(in, out, s)
}

func autoConvert_gdc_BackupBucketConfig_To_v1alpha1_BackupBucketConfig(in *gdc.BackupBucketConfig, out *BackupBucketConfig, s conversion.Scope) error {
	out.DualZoneBucketLocation = in.DualZoneBucketLocation
	out.RequestChecksumCalculation = in.RequestChecksumCalculation
	out.ResponseChecksumValidation = in.ResponseChecksumValidation
	return nil
}

// Convert_gdc_BackupBucketConfig_To_v1alpha1_BackupBucketConfig is an autogenerated conversion function.
func Convert_gdc_BackupBucketConfig_To_v1alpha1_BackupBucketConfig(in *gdc.BackupBucketConfig, out *BackupBucketConfig, s conversion.Scope) error {
	return autoConvert_gdc_BackupBucketConfig_To_v1alpha1_BackupBucketConfig(in, out, s)
}

func autoConvert_v1alpha1_CloudProfileConfig_To_gdc_CloudProfileConfig(in *CloudProfileConfig, out *gdc.CloudProfileConfig, s conversion.Scope) error {
	out.MachineImages = *(*[]gdc.MachineImages)(unsafe.Pointer(&in.MachineImages))
	out.OrgConfig = (*gdc.OrgConfig)(unsafe.Pointer(in.OrgConfig))
	return nil
}

// Convert_v1alpha1_CloudProfileConfig_To_gdc_CloudProfileConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudProfileConfig_To_gdc_CloudProfileConfig(in *CloudProfileConfig, out *gdc.CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudProfileConfig_To_gdc_CloudProfileConfig(in, out, s)
}

func autoConvert_gdc_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *gdc.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	out.MachineImages = *(*[]MachineImages)(unsafe.Pointer(&in.MachineImages))
	out.OrgConfig = (*OrgConfig)(unsafe.Pointer(in.OrgConfig))
	return nil
}

// Convert_gdc_CloudProfileConfig_To_v1alpha1_CloudProfileConfig is an autogenerated conversion function.
func Convert_gdc_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *gdc.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_gdc_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in, out, s)
}

func autoConvert_v1alpha1_ControlPlaneConfig_To_gdc_ControlPlaneConfig(in *ControlPlaneConfig, out *gdc.ControlPlaneConfig, s conversion.Scope) error {
	out.Zone = in.Zone
	out.Storage = (*gdc.Storage)(unsafe.Pointer(in.Storage))
	return nil
}

// Convert_v1alpha1_ControlPlaneConfig_To_gdc_ControlPlaneConfig is an autogenerated conversion function.
func Convert_v1alpha1_ControlPlaneConfig_To_gdc_ControlPlaneConfig(in *ControlPlaneConfig, out *gdc.ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControlPlaneConfig_To_gdc_ControlPlaneConfig(in, out, s)
}

func autoConvert_gdc_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *gdc.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	out.Zone = in.Zone
	out.Storage = (*Storage)(unsafe.Pointer(in.Storage))
	return nil
}

// Convert_gdc_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig is an autogenerated conversion function.
func Convert_gdc_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *gdc.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_gdc_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureConfig_To_gdc_InfrastructureConfig(in *InfrastructureConfig, out *gdc.InfrastructureConfig, s conversion.Scope) error {
	if err := Convert_v1alpha1_NetworkConfig_To_gdc_NetworkConfig(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	out.EnableEgress = (*bool)(unsafe.Pointer(in.EnableEgress))
	return nil
}

// Convert_v1alpha1_InfrastructureConfig_To_gdc_InfrastructureConfig is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureConfig_To_gdc_InfrastructureConfig(in *InfrastructureConfig, out *gdc.InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureConfig_To_gdc_InfrastructureConfig(in, out, s)
}

func autoConvert_gdc_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *gdc.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	if err := Convert_gdc_NetworkConfig_To_v1alpha1_NetworkConfig(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	out.EnableEgress = (*bool)(unsafe.Pointer(in.EnableEgress))
	return nil
}

// Convert_gdc_InfrastructureConfig_To_v1alpha1_InfrastructureConfig is an autogenerated conversion function.
func Convert_gdc_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *gdc.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_gdc_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureStatus_To_gdc_InfrastructureStatus(in *InfrastructureStatus, out *gdc.InfrastructureStatus, s conversion.Scope) error {
	out.EnableEgress = (*bool)(unsafe.Pointer(in.EnableEgress))
	if err := Convert_v1alpha1_NetworkStatus_To_gdc_NetworkStatus(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_InfrastructureStatus_To_gdc_InfrastructureStatus is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureStatus_To_gdc_InfrastructureStatus(in *InfrastructureStatus, out *gdc.InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureStatus_To_gdc_InfrastructureStatus(in, out, s)
}

func autoConvert_gdc_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *gdc.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	out.EnableEgress = (*bool)(unsafe.Pointer(in.EnableEgress))
	if err := Convert_gdc_NetworkStatus_To_v1alpha1_NetworkStatus(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	return nil
}

// Convert_gdc_InfrastructureStatus_To_v1alpha1_InfrastructureStatus is an autogenerated conversion function.
func Convert_gdc_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *gdc.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_gdc_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in, out, s)
}

func autoConvert_v1alpha1_MachineImage_To_gdc_MachineImage(in *MachineImage, out *gdc.MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Project = in.Project
	out.Version = in.Version
	out.Image = in.Image
	out.Architecture = (*string)(unsafe.Pointer(in.Architecture))
	return nil
}

// Convert_v1alpha1_MachineImage_To_gdc_MachineImage is an autogenerated conversion function.
func Convert_v1alpha1_MachineImage_To_gdc_MachineImage(in *MachineImage, out *gdc.MachineImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImage_To_gdc_MachineImage(in, out, s)
}

func autoConvert_gdc_MachineImage_To_v1alpha1_MachineImage(in *gdc.MachineImage, out *MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Project = in.Project
	out.Version = in.Version
	out.Image = in.Image
	out.Architecture = (*string)(unsafe.Pointer(in.Architecture))
	return nil
}

// Convert_gdc_MachineImage_To_v1alpha1_MachineImage is an autogenerated conversion function.
func Convert_gdc_MachineImage_To_v1alpha1_MachineImage(in *gdc.MachineImage, out *MachineImage, s conversion.Scope) error {
	return autoConvert_gdc_MachineImage_To_v1alpha1_MachineImage(in, out, s)
}

func autoConvert_v1alpha1_MachineImageFlavor_To_gdc_MachineImageFlavor(in *MachineImageFlavor, out *gdc.MachineImageFlavor, s conversion.Scope) error {
	out.Capabilities = *(*v1beta1.Capabilities)(unsafe.Pointer(&in.Capabilities))
	out.Image = in.Image
	return nil
}

// Convert_v1alpha1_MachineImageFlavor_To_gdc_MachineImageFlavor is an autogenerated conversion function.
func Convert_v1alpha1_MachineImageFlavor_To_gdc_MachineImageFlavor(in *MachineImageFlavor, out *gdc.MachineImageFlavor, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImageFlavor_To_gdc_MachineImageFlavor(in, out, s)
}

func autoConvert_gdc_MachineImageFlavor_To_v1alpha1_MachineImageFlavor(in *gdc.MachineImageFlavor, out *MachineImageFlavor, s conversion.Scope) error {
	out.Capabilities = *(*v1beta1.Capabilities)(unsafe.Pointer(&in.Capabilities))
	out.Image = in.Image
	return nil
}

// Convert_gdc_MachineImageFlavor_To_v1alpha1_MachineImageFlavor is an autogenerated conversion function.
func Convert_gdc_MachineImageFlavor_To_v1alpha1_MachineImageFlavor(in *gdc.MachineImageFlavor, out *MachineImageFlavor, s conversion.Scope) error {
	return autoConvert_gdc_MachineImageFlavor_To_v1alpha1_MachineImageFlavor(in, out, s)
}

func autoConvert_v1alpha1_MachineImageVersion_To_gdc_MachineImageVersion(in *MachineImageVersion, out *gdc.MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.Image = in.Image
	out.Architecture = (*string)(unsafe.Pointer(in.Architecture))
	out.CapabilityFlavors = *(*[]gdc.MachineImageFlavor)(unsafe.Pointer(&in.CapabilityFlavors))
	return nil
}

// Convert_v1alpha1_MachineImageVersion_To_gdc_MachineImageVersion is an autogenerated conversion function.
func Convert_v1alpha1_MachineImageVersion_To_gdc_MachineImageVersion(in *MachineImageVersion, out *gdc.MachineImageVersion, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImageVersion_To_gdc_MachineImageVersion(in, out, s)
}

func autoConvert_gdc_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *gdc.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.Image = in.Image
	out.Architecture = (*string)(unsafe.Pointer(in.Architecture))
	out.CapabilityFlavors = *(*[]MachineImageFlavor)(unsafe.Pointer(&in.CapabilityFlavors))
	return nil
}

// Convert_gdc_MachineImageVersion_To_v1alpha1_MachineImageVersion is an autogenerated conversion function.
func Convert_gdc_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *gdc.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	return autoConvert_gdc_MachineImageVersion_To_v1alpha1_MachineImageVersion(in, out, s)
}

func autoConvert_v1alpha1_MachineImages_To_gdc_MachineImages(in *MachineImages, out *gdc.MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Project = in.Project
	out.Versions = *(*[]gdc.MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_v1alpha1_MachineImages_To_gdc_MachineImages is an autogenerated conversion function.
func Convert_v1alpha1_MachineImages_To_gdc_MachineImages(in *MachineImages, out *gdc.MachineImages, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImages_To_gdc_MachineImages(in, out, s)
}

func autoConvert_gdc_MachineImages_To_v1alpha1_MachineImages(in *gdc.MachineImages, out *MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Project = in.Project
	out.Versions = *(*[]MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_gdc_MachineImages_To_v1alpha1_MachineImages is an autogenerated conversion function.
func Convert_gdc_MachineImages_To_v1alpha1_MachineImages(in *gdc.MachineImages, out *MachineImages, s conversion.Scope) error {
	return autoConvert_gdc_MachineImages_To_v1alpha1_MachineImages(in, out, s)
}

func autoConvert_v1alpha1_NetworkConfig_To_gdc_NetworkConfig(in *NetworkConfig, out *gdc.NetworkConfig, s conversion.Scope) error {
	out.ParentAddressPoolClaim = in.ParentAddressPoolClaim
	out.NodeCIDR = in.NodeCIDR
	out.ParentSubnet = in.ParentSubnet
	out.ParentSubnetProject = in.ParentSubnetProject
	out.ParentReference = (*gdc.SubnetReference)(unsafe.Pointer(in.ParentReference))
	out.Zones = *(*[]gdc.Zone)(unsafe.Pointer(&in.Zones))
	return nil
}

// Convert_v1alpha1_NetworkConfig_To_gdc_NetworkConfig is an autogenerated conversion function.
func Convert_v1alpha1_NetworkConfig_To_gdc_NetworkConfig(in *NetworkConfig, out *gdc.NetworkConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkConfig_To_gdc_NetworkConfig(in, out, s)
}

func autoConvert_gdc_NetworkConfig_To_v1alpha1_NetworkConfig(in *gdc.NetworkConfig, out *NetworkConfig, s conversion.Scope) error {
	out.ParentAddressPoolClaim = in.ParentAddressPoolClaim
	out.NodeCIDR = in.NodeCIDR
	out.ParentSubnet = in.ParentSubnet
	out.ParentSubnetProject = in.ParentSubnetProject
	out.ParentReference = (*SubnetReference)(unsafe.Pointer(in.ParentReference))
	out.Zones = *(*[]Zone)(unsafe.Pointer(&in.Zones))
	return nil
}

// Convert_gdc_NetworkConfig_To_v1alpha1_NetworkConfig is an autogenerated conversion function.
func Convert_gdc_NetworkConfig_To_v1alpha1_NetworkConfig(in *gdc.NetworkConfig, out *NetworkConfig, s conversion.Scope) error {
	return autoConvert_gdc_NetworkConfig_To_v1alpha1_NetworkConfig(in, out, s)
}

func autoConvert_v1alpha1_NetworkStatus_To_gdc_NetworkStatus(in *NetworkStatus, out *gdc.NetworkStatus, s conversion.Scope) error {
	out.NodeAddressPoolClaim = in.NodeAddressPoolClaim
	out.NodeCIDR = in.NodeCIDR
	out.NodeSubnet = in.NodeSubnet
	out.Zones = *(*[]gdc.Zones)(unsafe.Pointer(&in.Zones))
	return nil
}

// Convert_v1alpha1_NetworkStatus_To_gdc_NetworkStatus is an autogenerated conversion function.
func Convert_v1alpha1_NetworkStatus_To_gdc_NetworkStatus(in *NetworkStatus, out *gdc.NetworkStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkStatus_To_gdc_NetworkStatus(in, out, s)
}

func autoConvert_gdc_NetworkStatus_To_v1alpha1_NetworkStatus(in *gdc.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	out.NodeAddressPoolClaim = in.NodeAddressPoolClaim
	out.NodeCIDR = in.NodeCIDR
	out.NodeSubnet = in.NodeSubnet
	out.Zones = *(*[]Zones)(unsafe.Pointer(&in.Zones))
	return nil
}

// Convert_gdc_NetworkStatus_To_v1alpha1_NetworkStatus is an autogenerated conversion function.
func Convert_gdc_NetworkStatus_To_v1alpha1_NetworkStatus(in *gdc.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	return autoConvert_gdc_NetworkStatus_To_v1alpha1_NetworkStatus(in, out, s)
}

func autoConvert_v1alpha1_OrgConfig_To_gdc_OrgConfig(in *OrgConfig, out *gdc.OrgConfig, s conversion.Scope) error {
	out.OrgName = in.OrgName
	out.GlobalManagementAPI = in.GlobalManagementAPI
	out.RegistryURL = in.RegistryURL
	out.CAData = in.CAData
	out.Zones = *(*[]*gdc.ZoneEndpoints)(unsafe.Pointer(&in.Zones))
	return nil
}

// Convert_v1alpha1_OrgConfig_To_gdc_OrgConfig is an autogenerated conversion function.
func Convert_v1alpha1_OrgConfig_To_gdc_OrgConfig(in *OrgConfig, out *gdc.OrgConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_OrgConfig_To_gdc_OrgConfig(in, out, s)
}

func autoConvert_gdc_OrgConfig_To_v1alpha1_OrgConfig(in *gdc.OrgConfig, out *OrgConfig, s conversion.Scope) error {
	out.OrgName = in.OrgName
	out.GlobalManagementAPI = in.GlobalManagementAPI
	out.RegistryURL = in.RegistryURL
	out.CAData = in.CAData
	out.Zones = *(*[]*ZoneEndpoints)(unsafe.Pointer(&in.Zones))
	return nil
}

// Convert_gdc_OrgConfig_To_v1alpha1_OrgConfig is an autogenerated conversion function.
func Convert_gdc_OrgConfig_To_v1alpha1_OrgConfig(in *gdc.OrgConfig, out *OrgConfig, s conversion.Scope) error {
	return autoConvert_gdc_OrgConfig_To_v1alpha1_OrgConfig(in, out, s)
}

func autoConvert_v1alpha1_Storage_To_gdc_Storage(in *Storage, out *gdc.Storage, s conversion.Scope) error {
	out.ManagedDefaultStorageClass = (*bool)(unsafe.Pointer(in.ManagedDefaultStorageClass))
	out.ManagedDefaultVolumeSnapshotClass = (*bool)(unsafe.Pointer(in.ManagedDefaultVolumeSnapshotClass))
	return nil
}

// Convert_v1alpha1_Storage_To_gdc_Storage is an autogenerated conversion function.
func Convert_v1alpha1_Storage_To_gdc_Storage(in *Storage, out *gdc.Storage, s conversion.Scope) error {
	return autoConvert_v1alpha1_Storage_To_gdc_Storage(in, out, s)
}

func autoConvert_gdc_Storage_To_v1alpha1_Storage(in *gdc.Storage, out *Storage, s conversion.Scope) error {
	out.ManagedDefaultStorageClass = (*bool)(unsafe.Pointer(in.ManagedDefaultStorageClass))
	out.ManagedDefaultVolumeSnapshotClass = (*bool)(unsafe.Pointer(in.ManagedDefaultVolumeSnapshotClass))
	return nil
}

// Convert_gdc_Storage_To_v1alpha1_Storage is an autogenerated conversion function.
func Convert_gdc_Storage_To_v1alpha1_Storage(in *gdc.Storage, out *Storage, s conversion.Scope) error {
	return autoConvert_gdc_Storage_To_v1alpha1_Storage(in, out, s)
}

func autoConvert_v1alpha1_SubnetReference_To_gdc_SubnetReference(in *SubnetReference, out *gdc.SubnetReference, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = (*string)(unsafe.Pointer(in.Namespace))
	out.Type = gdc.ReferenceType(in.Type)
	return nil
}

// Convert_v1alpha1_SubnetReference_To_gdc_SubnetReference is an autogenerated conversion function.
func Convert_v1alpha1_SubnetReference_To_gdc_SubnetReference(in *SubnetReference, out *gdc.SubnetReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_SubnetReference_To_gdc_SubnetReference(in, out, s)
}

func autoConvert_gdc_SubnetReference_To_v1alpha1_SubnetReference(in *gdc.SubnetReference, out *SubnetReference, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = (*string)(unsafe.Pointer(in.Namespace))
	out.Type = ReferenceType(in.Type)
	return nil
}

// Convert_gdc_SubnetReference_To_v1alpha1_SubnetReference is an autogenerated conversion function.
func Convert_gdc_SubnetReference_To_v1alpha1_SubnetReference(in *gdc.SubnetReference, out *SubnetReference, s conversion.Scope) error {
	return autoConvert_gdc_SubnetReference_To_v1alpha1_SubnetReference(in, out, s)
}

func autoConvert_v1alpha1_WorkerConfig_To_gdc_WorkerConfig(in *WorkerConfig, out *gdc.WorkerConfig, s conversion.Scope) error {
	out.NodeTemplate = (*extensionsv1alpha1.NodeTemplate)(unsafe.Pointer(in.NodeTemplate))
	return nil
}

// Convert_v1alpha1_WorkerConfig_To_gdc_WorkerConfig is an autogenerated conversion function.
func Convert_v1alpha1_WorkerConfig_To_gdc_WorkerConfig(in *WorkerConfig, out *gdc.WorkerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkerConfig_To_gdc_WorkerConfig(in, out, s)
}

func autoConvert_gdc_WorkerConfig_To_v1alpha1_WorkerConfig(in *gdc.WorkerConfig, out *WorkerConfig, s conversion.Scope) error {
	out.NodeTemplate = (*extensionsv1alpha1.NodeTemplate)(unsafe.Pointer(in.NodeTemplate))
	return nil
}

// Convert_gdc_WorkerConfig_To_v1alpha1_WorkerConfig is an autogenerated conversion function.
func Convert_gdc_WorkerConfig_To_v1alpha1_WorkerConfig(in *gdc.WorkerConfig, out *WorkerConfig, s conversion.Scope) error {
	return autoConvert_gdc_WorkerConfig_To_v1alpha1_WorkerConfig(in, out, s)
}

func autoConvert_v1alpha1_WorkerStatus_To_gdc_WorkerStatus(in *WorkerStatus, out *gdc.WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]gdc.MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_v1alpha1_WorkerStatus_To_gdc_WorkerStatus is an autogenerated conversion function.
func Convert_v1alpha1_WorkerStatus_To_gdc_WorkerStatus(in *WorkerStatus, out *gdc.WorkerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkerStatus_To_gdc_WorkerStatus(in, out, s)
}

func autoConvert_gdc_WorkerStatus_To_v1alpha1_WorkerStatus(in *gdc.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_gdc_WorkerStatus_To_v1alpha1_WorkerStatus is an autogenerated conversion function.
func Convert_gdc_WorkerStatus_To_v1alpha1_WorkerStatus(in *gdc.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	return autoConvert_gdc_WorkerStatus_To_v1alpha1_WorkerStatus(in, out, s)
}

func autoConvert_v1alpha1_Zone_To_gdc_Zone(in *Zone, out *gdc.Zone, s conversion.Scope) error {
	out.Name = in.Name
	out.CIDR = in.CIDR
	return nil
}

// Convert_v1alpha1_Zone_To_gdc_Zone is an autogenerated conversion function.
func Convert_v1alpha1_Zone_To_gdc_Zone(in *Zone, out *gdc.Zone, s conversion.Scope) error {
	return autoConvert_v1alpha1_Zone_To_gdc_Zone(in, out, s)
}

func autoConvert_gdc_Zone_To_v1alpha1_Zone(in *gdc.Zone, out *Zone, s conversion.Scope) error {
	out.Name = in.Name
	out.CIDR = in.CIDR
	return nil
}

// Convert_gdc_Zone_To_v1alpha1_Zone is an autogenerated conversion function.
func Convert_gdc_Zone_To_v1alpha1_Zone(in *gdc.Zone, out *Zone, s conversion.Scope) error {
	return autoConvert_gdc_Zone_To_v1alpha1_Zone(in, out, s)
}

func autoConvert_v1alpha1_ZoneEndpoints_To_gdc_ZoneEndpoints(in *ZoneEndpoints, out *gdc.ZoneEndpoints, s conversion.Scope) error {
	out.Name = in.Name
	out.ManagementAPI = in.ManagementAPI
	out.InfrastructureAPI = in.InfrastructureAPI
	return nil
}

// Convert_v1alpha1_ZoneEndpoints_To_gdc_ZoneEndpoints is an autogenerated conversion function.
func Convert_v1alpha1_ZoneEndpoints_To_gdc_ZoneEndpoints(in *ZoneEndpoints, out *gdc.ZoneEndpoints, s conversion.Scope) error {
	return autoConvert_v1alpha1_ZoneEndpoints_To_gdc_ZoneEndpoints(in, out, s)
}

func autoConvert_gdc_ZoneEndpoints_To_v1alpha1_ZoneEndpoints(in *gdc.ZoneEndpoints, out *ZoneEndpoints, s conversion.Scope) error {
	out.Name = in.Name
	out.ManagementAPI = in.ManagementAPI
	out.InfrastructureAPI = in.InfrastructureAPI
	return nil
}

// Convert_gdc_ZoneEndpoints_To_v1alpha1_ZoneEndpoints is an autogenerated conversion function.
func Convert_gdc_ZoneEndpoints_To_v1alpha1_ZoneEndpoints(in *gdc.ZoneEndpoints, out *ZoneEndpoints, s conversion.Scope) error {
	return autoConvert_gdc_ZoneEndpoints_To_v1alpha1_ZoneEndpoints(in, out, s)
}

func autoConvert_v1alpha1_Zones_To_gdc_Zones(in *Zones, out *gdc.Zones, s conversion.Scope) error {
	out.Name = in.Name
	out.Subnet = in.Subnet
	return nil
}

// Convert_v1alpha1_Zones_To_gdc_Zones is an autogenerated conversion function.
func Convert_v1alpha1_Zones_To_gdc_Zones(in *Zones, out *gdc.Zones, s conversion.Scope) error {
	return autoConvert_v1alpha1_Zones_To_gdc_Zones(in, out, s)
}

func autoConvert_gdc_Zones_To_v1alpha1_Zones(in *gdc.Zones, out *Zones, s conversion.Scope) error {
	out.Name = in.Name
	out.Subnet = in.Subnet
	return nil
}

// Convert_gdc_Zones_To_v1alpha1_Zones is an autogenerated conversion function.
func Convert_gdc_Zones_To_v1alpha1_Zones(in *gdc.Zones, out *Zones, s conversion.Scope) error {
	return autoConvert_gdc_Zones_To_v1alpha1_Zones(in, out, s)
}
