# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
{{-  if .Values.ignoreResources }}
  annotations:
    resources.gardener.cloud/ignore: "true"
{{- end }}
  labels:
{{ include "labels" . | indent 4 }}
    high-availability-config.resources.gardener.cloud/type: server
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "labels" . | indent 6 }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable }}
      maxSurge: {{ .Values.maxSurge }}
  template:
    metadata:
      annotations:
        checksum/configmap-{{ include "name" . }}-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if and .Values.metrics.enableScraping }}
        prometheus.io/name: "{{ .Release.Name }}"
        prometheus.io/scrape: "true"
        # default metrics endpoint in controller-runtime
        prometheus.io/port: "{{ .Values.metricsPort }}"
        {{- end }}
      labels:
        networking.gardener.cloud/to-runtime-apiserver: allowed
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-public-networks: allowed
        networking.gardener.cloud/to-private-networks: allowed
        networking.resources.gardener.cloud/to-all-shoots-kube-apiserver-tcp-443: allowed
{{ include "labels" . | indent 8 }}
    spec:
      {{- if .Values.gardener.runtimeCluster.enabled }}
      priorityClassName: {{ .Values.gardener.runtimeCluster.priorityClassName }}
      {{- else if not .Values.skipPriorityClassName }}
      priorityClassName: gardener-system-900
      {{- end }}
      serviceAccountName: {{ include "name" . }}
      containers:
      - name: {{ include "name" . }}
        image: {{ include "image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /extension-provider
        - --config-file=/etc/{{ include "name" . }}/config/config.yaml
        - --backupbucket-max-concurrent-reconciles={{ .Values.controllers.backupbucket.concurrentSyncs }}
        - --backupentry-max-concurrent-reconciles={{ .Values.controllers.backupentry.concurrentSyncs }}
        - --controlplane-max-concurrent-reconciles={{ .Values.controllers.controlplane.concurrentSyncs }}
        - --dnsrecord-max-concurrent-reconciles={{ .Values.controllers.dnsrecord.concurrentSyncs }}
        - --infrastructure-max-concurrent-reconciles={{ .Values.controllers.infrastructure.concurrentSyncs }}
        - --ignore-operation-annotation={{ .Values.controllers.ignoreOperationAnnotation }}
        - --worker-max-concurrent-reconciles={{ .Values.controllers.worker.concurrentSyncs }}
        - --webhook-config-namespace={{ .Release.Namespace }}
        - --webhook-config-service-port={{ .Values.webhookConfig.servicePort }}
        - --webhook-config-server-port={{ .Values.webhookConfig.serverPort }}
        {{- if .Values.gardener.runtimeCluster.enabled }}
        - --controllers=backupbucket,backupentry,dnsrecord
        - --disable-webhooks=controlplane,shoot
        - --extension-classes=garden
        {{- else }}
        - --disable-controllers={{ .Values.disableControllers | join "," }}
        - --disable-webhooks={{ .Values.disableWebhooks | join "," }}
        {{- end }}
        {{- if .Values.metricsPort }}
        - --metrics-bind-address=:{{ .Values.metricsPort }}
        {{- end }}
        - --health-bind-address=:{{ .Values.healthPort }}
        - --gardener-version={{ .Values.gardener.version }}
        env:
        - name: LEADER_ELECTION_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WEBHOOK_CONFIG_NAMESPACE
          value: {{ .Release.Namespace }}
        {{- if .Values.imageVectorOverwrite }}
        - name: IMAGEVECTOR_OVERWRITE
          value: /charts_overwrite/images_overwrite.yaml
        {{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.healthPort }}
            scheme: HTTP
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.healthPort }}
            scheme: HTTP
          initialDelaySeconds: 5
        ports:
        - name: webhook-server
          containerPort: {{ .Values.webhookConfig.serverPort }}
          protocol: TCP
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | nindent 10 }}
{{- end }}
        volumeMounts:
        - name: config
          mountPath: /etc/{{ include "name" . }}/config
        {{- if .Values.imageVectorOverwrite }}
        - name: imagevector-overwrite
          mountPath: /charts_overwrite/
          readOnly: true
        {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: {{ include "labels.app.key" . }}
                operator: In
                values:
                - {{ include "labels.app.value" . }}
            topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: config
        configMap:
          name: {{ include "name" . }}-configmap
          defaultMode: 420
      {{- if .Values.imageVectorOverwrite }}
      - name: imagevector-overwrite
        configMap:
          name: {{ include "name" . }}-imagevector-overwrite
          defaultMode: 420
      {{- end }}
      imagePullSecrets:
      {{- with .Values.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
