# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

socketPath: /csi/csi.sock
topologyKey:
images:
  csi-driver: 10.200.9.2:10443/library/private-cloud-devel/gardener/kubevirt-csi-driver:v1
  csi-node-driver-registrar: 10.200.9.2:10443/library/private-cloud-devel/gardener/origin-csi-node-driver-registrar:latest
  csi-liveness-probe: 10.200.9.2:10443/library/private-cloud-devel/gardener/origin-csi-livenessprobe:latest
resources:
  driver:
    requests:
      cpu: 20m
      memory: 50Mi
  nodeDriverRegistrar:
    requests:
      cpu: 11m
      memory: 32Mi
  livenessProbe:
    requests:
      cpu: 11m
      memory: 32Mi
